#!/usr/bin/env python3
"""
Regenerates src/pythonScriptText.ts (the web app's "Python Script Exporter" download)
from unicore_um960_tracker.py, with um960_core.py inlined so the download is a single
self-contained file.

Usage:
  python3 gen_python_script_text.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
IMPORT_LINE = "from um960_core import convert_coordinates, UM960Configurator\n"


def build_standalone_script():
    with open(os.path.join(HERE, "unicore_um960_tracker.py"), encoding="utf-8") as f:
        tracker = f.read()
    with open(os.path.join(HERE, "um960_core.py"), encoding="utf-8") as f:
        core = f.read()

    # Drop the core module docstring, the tracker's own docstring describes the script
    core = re.sub(r'\A"""(.*?)"""\n', "", core, count=1, flags=re.DOTALL).lstrip("\n")
    if tracker.count(IMPORT_LINE) != 1:
        raise SystemExit(f"Expected exactly one '{IMPORT_LINE.strip()}' in unicore_um960_tracker.py")
    return tracker.replace(IMPORT_LINE, f"# --- Inlined from um960_core.py ---\n{core}# --- End of um960_core.py ---\n")


def to_template_literal(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def main():
    script = build_standalone_script()
    out_path = os.path.join(HERE, "src", "pythonScriptText.ts")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/**\n"
                " * @license\n"
                " * SPDX-License-Identifier: Apache-2.0\n"
                " *\n"
                " * Generated by gen_python_script_text.py from unicore_um960_tracker.py and um960_core.py.\n"
                " * Do not edit by hand.\n"
                " */\n\n"
                f"export const PYTHON_SCRIPT_TEXT = `{to_template_literal(script)}`;\n")
    print(f"Wrote {out_path} ({len(script.splitlines())} lines of Python)")


if __name__ == "__main__":
    main()
