/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by gen_python_script_text.py from unicore_um960_tracker.py and um960_core.py.
 * Do not edit by hand.
 */

export const PYTHON_SCRIPT_TEXT = `#!/usr/bin/env python3
"""
Unicore UM960 GNSS RTK NMEA Decoder and Real-time Tracker
---------------------------------------------------------
https://github.com/triochi/um960_gui

This script reads real-time NMEA stream from the Unicore UM960 module,
decodes position, RTK fix quality, DOP, heading, and satellite details,
converts the WGS84 geographic coordinates to Bulgarian BGS2005 UTM Zone 34N
and Greek HGRS87 / Greek Grid, and plots the real-time tracking trajectory.

Prerequisites:
  pip install pyserial pyproj matplotlib

Usage:
  python3 unicore_um960_tracker.py --port /dev/ttyUSB0 --baud 115200
  (Or use --simulate to run a demo without hardware!)
"""

import sys
import os
import time
import argparse
import math
import random
import threading
from collections import deque

# Silence harmless Qt/QPA Wayland warnings (e.g., QWindow::requestActivate() messages)
os.environ["QT_LOGGING_RULES"] = "qt.qpa.wayland=false"

try:
    import serial
except ImportError:
    print("Warning: 'pyserial' not installed. Live serial connection will not work.", file=sys.stderr)
    serial = None

try:
    import matplotlib.pyplot as plt
    from matplotlib.animation import FuncAnimation
except ImportError:
    print("Error: 'matplotlib' is required for real-time potting. Install with 'pip install matplotlib'.")
    sys.exit(1)


# --- Inlined from um960_core.py ---
import sys
import math
import time

try:
    import pyproj
except ImportError:
    print("Error: 'pyproj' is required for coordinate conversions. Install with 'pip install pyproj'.")
    sys.exit(1)


# -------------------------------------------------------------------------
# COORDINATE CONVERSIONS (pyproj transformers with multiple fallbacks)
# -------------------------------------------------------------------------
# EPSG:4326 - WGS84 Geographic Lat/Lon
# EPSG:7803 - BGS2005 / UTM zone 34N (Western Bulgaria)
# EPSG:7801 - BGS2005 / CCS2005 (Bulgarian National Lambert)
# EPSG:2100 - GGRS87 / Greek Grid (Greece national grid used for Cadastre)

wgs84_to_bgs_utm_transformer = None
wgs84_to_bgs_lam_transformer = None
wgs84_to_greek_transformer = None

# 1. BGS2005 / UTM Zone 34N (Try EPSG:7803, custom PROJ4 string, or standard EPSG:32634)
utm_candidates = [
    "EPSG:7803",
    "+proj=utm +zone=34 +ellps=GRS80 +units=m +no_defs",
    "EPSG:32634"
]
for crs_to in utm_candidates:
    try:
        wgs84_to_bgs_utm_transformer = pyproj.Transformer.from_crs("EPSG:4326", crs_to, always_xy=True)
        break
    except Exception:
        continue

# 2. BGS2005 / CCS2005 Lambert (Try EPSG:7801, or the equivalent PROJ4 string)
lambert_candidates = [
    "EPSG:7801",
    "+proj=lcc +lat_0=42.6678756833333 +lon_0=25.5 +lat_1=42 +lat_2=43.3333333333333 +x_0=500000 +y_0=4725824.3591 +ellps=GRS80 +units=m +no_defs"
]
for crs_to in lambert_candidates:
    try:
        wgs84_to_bgs_lam_transformer = pyproj.Transformer.from_crs("EPSG:4326", crs_to, always_xy=True)
        break
    except Exception:
        continue

# 3. GGRS87 / Greek Grid (Try EPSG:2100, or custom PROJ4 string)
greek_candidates = [
    "EPSG:2100",
    "+proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=-199.87,74.79,246.62,0,0,0,0 +units=m +no_defs"
]
for crs_to in greek_candidates:
    try:
        wgs84_to_greek_transformer = pyproj.Transformer.from_crs("EPSG:4326", crs_to, always_xy=True)
        break
    except Exception:
        continue

# Print warning status instead of crashing to allow execution to proceed
if not wgs84_to_bgs_utm_transformer:
    print("Warning: BGS UTM 34N Transformer could not be initialized. Visualizer will fall back to manual mathematical approximation.", file=sys.stderr)
if not wgs84_to_bgs_lam_transformer:
    print("Warning: BGS Lambert Transformer could not be initialized.", file=sys.stderr)
if not wgs84_to_greek_transformer:
    print("Warning: Greek Grid Transformer could not be initialized.", file=sys.stderr)


def convert_coordinates(lat, lon):
    """
    Transforms WGS84 latitude and longitude to Bulgarian BGS2005 and Greek Grid grids.
    Returns: (bgs_east, bgs_north, bgs_lam_east, bgs_lam_north, gr_east, gr_north)
    """
    bgs_e, bgs_n = float('nan'), float('nan')
    bgs_le, bgs_ln = float('nan'), float('nan')
    gr_e, gr_n = float('nan'), float('nan')

    # Convert to UTM Zone 34N
    if wgs84_to_bgs_utm_transformer:
        try:
            bgs_e, bgs_n = wgs84_to_bgs_utm_transformer.transform(lon, lat)
        except Exception:
            pass

    # High-precision manual mathematical approximation for UTM Zone 34N if pyproj solver fails
    if (math.isnan(bgs_e) or math.isnan(bgs_n)) and not (math.isnan(lat) or math.isnan(lon)):
        try:
            # Central meridian for UTM Zone 34 is 21.0 degrees longitude
            dlon = (lon - 21.0) * math.pi / 180.0
            lat_rad = lat * math.pi / 180.0
            k0 = 0.9996
            fe = 500000.0
            a = 6378137.0
            e2 = 0.00669437999014

            # Meridional distance
            M = (6367449.1458 * lat_rad -
                 16038.5087 * math.sin(2.0 * lat_rad) +
                 16.8326 * math.sin(4.0 * lat_rad) -
                 0.0220 * math.sin(6.0 * lat_rad))

            N = a / math.sqrt(1.0 - e2 * math.sin(lat_rad)**2)
            T = math.tan(lat_rad)**2
            C = e2 / (1.0 - e2) * math.cos(lat_rad)**2
            A = dlon * math.cos(lat_rad)

            bgs_e = fe + k0 * N * (A + (1.0 - T + C) * A**3 / 6.0 + (5.0 - 18.0 * T + T**2 + 72.0 * C - 58.0 * e2) * A**5 / 120.0)
            bgs_n = k0 * (M + N * math.tan(lat_rad) * (A**2 / 2.0 + (5.0 - T + 9.0 * C + 4.0 * C**2) * A**4 / 24.0 + (61.0 - 58.0 * T + T**2 + 600.0 * C - 330.0 * e2) * A**6 / 720.0))
        except Exception:
            pass

    # Convert to Bulgarian National Lambert
    if wgs84_to_bgs_lam_transformer:
        try:
            bgs_le, bgs_ln = wgs84_to_bgs_lam_transformer.transform(lon, lat)
        except Exception:
            pass

    # Convert to Greek Grid
    if wgs84_to_greek_transformer:
        try:
            gr_e, gr_n = wgs84_to_greek_transformer.transform(lon, lat)
        except Exception:
            pass

    return bgs_e, bgs_n, bgs_le, bgs_ln, gr_e, gr_n


# -------------------------------------------------------------------------
# UM960 COMMAND INTERFACE (see SparkFun Unicore GNSS Arduino library)
#   Query:   "MODE"              -> #MODE,97,GPS,FINE,...;MODE ROVER SURVEY,*18
#   Command: "MODE ROVER SURVEY" -> $command,MODE ROVER SURVEY,response: OK*..
#   Errors contain "PARSING", e.g. $command,...,response: PARSING FAILD NO MATCHING FUNC ...
# -------------------------------------------------------------------------
class UM960Configurator:
    """
    Checks and adjusts the receiver configuration over an open serial connection.
    NMEA traffic received while waiting for command replies is passed to \`on_line\`,
    status messages go to \`log\`.
    """
    def __init__(self, serial_conn, on_line=None, log=print, rover_mode="SURVEY", check_mode=True,
                 save_config=False, nmea_messages=("GPGGA", "GPRMC"), nmea_interval=1.0, should_stop=None):
        self.serial = serial_conn
        self.on_line = on_line or (lambda line: None)
        self.log = log
        self.rover_mode = rover_mode      # ROVER sub-type: SURVEY, UAV, AUTOMOTIVE or "" for plain ROVER
        self.check_mode = check_mode      # Query MODE and switch to ROVER if needed
        self.save_config = save_config    # Persist configuration changes with SAVECONFIG
        self.nmea_messages = [m.upper() for m in nmea_messages]  # NMEA logs to enable (empty = skip)
        self.nmea_interval = nmea_interval  # Output interval in seconds (1 = 1Hz, 0.2 = 5Hz)
        self.should_stop = should_stop or (lambda: False)  # Aborts waiting for replies, e.g. on disconnect

    def _send_and_wait(self, command, match, timeout=3.0):
        """
        Sends a command and waits for a response line containing \`match\`.
        NMEA traffic received meanwhile is still passed to on_line.
        Returns the matching response line, or None on timeout.
        """
        self.serial.reset_input_buffer()
        self.serial.write(f"{command}\\r\\n".encode('ascii'))
        self.serial.flush()

        deadline = time.time() + timeout
        while time.time() < deadline and not self.should_stop():
            line_str = self.serial.readline().decode('ascii', errors='ignore').strip()
            if not line_str:
                continue
            if match.upper() in line_str.upper():
                return line_str
            self.on_line(line_str)
        return None

    def query_mode(self, attempts=2):
        """Returns the receiver's current mode string (e.g. 'MODE ROVER SURVEY'), or None."""
        # The first query after opening the port is occasionally lost, so retry once
        for _ in range(attempts):
            response = self._send_and_wait("MODE", "#MODE")
            if response and ';' in response:
                # '#MODE,...;MODE ROVER SURVEY,*18' -> 'MODE ROVER SURVEY'
                return response.split(';', 1)[1].split('*', 1)[0].strip(' ,')
        return None

    def query_loglist(self, timeout=2.0):
        """
        Returns (port, {message: interval_s}) for the messages logged on the port we are connected to.
        Reply format:
            <LOGLIST COM1 16528 98.000000 UNKNOWN 1 275.000000 276423 537 18
            <\\t1
            <\\tGPGGA COM1 1
        """
        if self._send_and_wait("LOGLIST", "$command,LOGLIST") is None:
            return None, None

        port, logs = None, {}
        deadline = time.time() + timeout
        while time.time() < deadline and not self.should_stop():
            line_str = self.serial.readline().decode('ascii', errors='ignore').strip()
            if not line_str.startswith('<'):
                if port is not None and not line_str:
                    break  # blank line terminates the list
                self.on_line(line_str)
                continue
            fields = line_str.lstrip('<').split()
            if fields and fields[0] == "LOGLIST" and len(fields) > 1:
                port = fields[1]
            elif len(fields) >= 3:
                try:
                    logs[(fields[0].upper(), fields[1].upper())] = float(fields[2])
                except ValueError:
                    pass
        if port is None:
            return None, None
        return port, {msg: rate for (msg, p), rate in logs.items() if p == port}

    def send_command(self, command, timeout=3.0):
        """Sends a configuration command. Returns True if the receiver replied with OK."""
        response = self._send_and_wait(command, f"$command,{command}", timeout)
        if response is None:
            self.log(f"UM960: no response to '{command}'")
            return False
        if "OK" not in response.upper():
            self.log(f"UM960: '{command}' rejected: {response}")
            return False
        return True

    def ensure_rover_mode(self):
        """
        Switches the UM960 to ROVER mode if it is currently configured as a BASE (or unknown).
        Returns (is_rover, changed).
        """
        current = self.query_mode()
        self.log(f"UM960 current mode: {current or 'unknown (no reply to MODE query)'}")
        if current and "ROVER" in current.upper():
            return True, False

        command = f"MODE ROVER {self.rover_mode}".strip()
        self.log(f"UM960: reconfiguring -> '{command}'")
        if not self.send_command(command):
            return False, False

        new_mode = self.query_mode()
        self.log(f"UM960 mode is now: {new_mode or 'unknown'}")
        return bool(new_mode and "ROVER" in new_mode.upper()), True

    def ensure_nmea_output(self):
        """
        Enables the configured NMEA messages on the port we are connected to, skipping ones
        already logged at the requested interval. Returns (ok, changed).
        """
        port, logs = self.query_loglist()
        if port is None:
            self.log("UM960: no reply to LOGLIST, enabling all NMEA messages")
            logs = {}
        else:
            active = ", ".join(f"{m}@{r:g}s" for m, r in logs.items()) or "none"
            self.log(f"UM960 connected on {port}, active logs: {active}")

        ok, enabled = True, []
        for msg in self.nmea_messages:
            if logs.get(msg) is not None and math.isclose(logs[msg], self.nmea_interval):
                continue
            # "<MSG> <interval>" applies to the port we are talking on
            if self.send_command(f"{msg} {self.nmea_interval:g}"):
                enabled.append(msg)
            else:
                ok = False
        if enabled:
            self.log(f"UM960: enabled {', '.join(enabled)} every {self.nmea_interval:g}s")
        return ok, bool(enabled)

    def configure(self):
        """Runs the enabled configuration steps and saves to NVM once if anything changed."""
        changed = False
        if self.check_mode:
            is_rover, mode_changed = self.ensure_rover_mode()
            changed |= mode_changed
            if not is_rover and not self.should_stop():
                self.log("Warning: could not confirm UM960 is in ROVER mode. Continuing anyway.")
        if self.should_stop():
            return
        if self.nmea_messages:
            nmea_ok, nmea_changed = self.ensure_nmea_output()
            changed |= nmea_changed
            if not nmea_ok:
                self.log("Warning: some NMEA messages could not be enabled.")

        if changed and self.save_config and not self.should_stop():
            if self.send_command("SAVECONFIG", timeout=5.0):
                self.log("UM960: configuration saved to NVM.")


# -------------------------------------------------------------------------
# NTRIP CLIENT (RTK corrections from a caster, e.g. igs-ip.net / EUREF / national networks)
# -------------------------------------------------------------------------
class NtripError(Exception):
    """Connection or protocol error; worth retrying."""


class NtripFatalError(NtripError):
    """Error that retrying will not fix (bad credentials, unknown mountpoint)."""


class NtripClient:
    """
    Minimal NTRIP client. Sends the request the way the tested feed_rtk scripts did
    (HTTP/1.1 with an 'Ntrip-Version: Ntrip/1.0' header), accepts both 'ICY 200 OK' (v1)
    and 'HTTP/1.x 200 OK' (v2) replies, and decodes chunked transfer encoding.
    """
    def __init__(self, host, port, mountpoint, user="", password="", timeout=10.0):
        self.host = host
        self.port = int(port)
        self.mountpoint = mountpoint.lstrip('/')
        self.user = user
        self.password = password
        self.timeout = timeout
        self.sock = None
        self._chunked = False
        self._leftover = b""   # data received together with the reply headers
        self._chunk_buf = b""  # incomplete chunk framing waiting for more data
        self._chunk_left = 0   # bytes remaining in the current chunk

    def connect(self):
        import base64
        import socket

        self.close()
        try:
            self.sock = socket.create_connection((self.host, self.port), timeout=self.timeout)
        except OSError as e:  # includes TimeoutError
            raise NtripError(f"cannot connect to {self.host}:{self.port}: {e}") from e

        request = (f"GET /{self.mountpoint} HTTP/1.1\\r\\n"
                   f"Host: {self.host}\\r\\n"
                   f"Ntrip-Version: Ntrip/1.0\\r\\n"
                   f"User-Agent: NTRIP UM960-GNSS-Dashboard/1.0\\r\\n")
        if self.user:
            token = base64.b64encode(f"{self.user}:{self.password}".encode('utf-8')).decode('ascii')
            request += f"Authorization: Basic {token}\\r\\n"
        request += "Accept: */*\\r\\nConnection: close\\r\\n\\r\\n"
        self.sock.sendall(request.encode('ascii'))

        # Read the status line (and headers for HTTP replies)
        data = b""
        while b"\\r\\n" not in data:
            data += self._recv_raw()
        status, rest = data.split(b"\\r\\n", 1)
        status_text = status.decode('latin-1').strip()

        if status_text.startswith("ICY 200"):
            self._leftover = rest
            return status_text
        if status_text.startswith("SOURCETABLE"):
            raise NtripFatalError(f"mountpoint '{self.mountpoint}' not found (caster returned its source table)")
        if not status_text.startswith("HTTP/"):
            raise NtripError(f"unexpected reply: {status_text[:80]}")

        while b"\\r\\n\\r\\n" not in b"\\r\\n" + rest:
            rest += self._recv_raw()
        headers, body = (b"\\r\\n" + rest).split(b"\\r\\n\\r\\n", 1)
        code = status_text.split()[1] if len(status_text.split()) > 1 else ""
        if code == "401":
            raise NtripFatalError("authorization failed (check user name and password)")
        if code in ("404", "400") or b"gnss/sourcetable" in headers.lower():
            raise NtripFatalError(f"mountpoint '{self.mountpoint}' not available ({status_text})")
        if code != "200":
            raise NtripError(f"caster replied: {status_text}")
        self._chunked = b"transfer-encoding: chunked" in headers.lower()
        self._leftover = body
        return status_text

    def _recv_raw(self):
        try:
            data = self.sock.recv(4096)
        except TimeoutError:
            raise  # no data within the socket timeout; the caller decides what to do
        except OSError as e:
            raise NtripError(f"connection error: {e}") from e
        if not data:
            raise NtripError("connection closed by caster")
        return data

    def read(self):
        """
        Returns the next block of correction data (may be b"" if only chunk framing arrived).
        Raises TimeoutError if nothing arrives within the socket timeout.
        """
        if self._leftover:
            data, self._leftover = self._leftover, b""
        else:
            data = self._recv_raw()
        if not self._chunked:
            return data
        data, self._chunk_buf = self._chunk_buf + data, b""
        return self._dechunk(data)

    def _dechunk(self, data):
        out = b""
        while data:
            if self._chunk_left:
                take = data[:self._chunk_left]
                out += take
                self._chunk_left -= len(take)
                data = data[len(take):]
                continue
            if data.startswith(b"\\r\\n"):
                data = data[2:]
                continue
            if b"\\r\\n" not in data:
                self._chunk_buf = data  # incomplete chunk size line, completed by the next read
                break
            size_line, data = data.split(b"\\r\\n", 1)
            try:
                self._chunk_left = int(size_line.split(b";")[0], 16)
            except ValueError:
                raise NtripError("malformed chunked data from caster")
            if self._chunk_left == 0:
                raise NtripError("caster ended the stream")
        return out

    def send_gga(self, gga_line):
        """Reports the receiver position to the caster (required by VRS / network mountpoints)."""
        try:
            self.sock.sendall((gga_line.strip() + "\\r\\n").encode('ascii'))
        except OSError as e:
            raise NtripError(f"connection error: {e}") from e

    def close(self):
        if self.sock:
            try:
                self.sock.close()
            except OSError:
                pass
        self.sock = None
        self._leftover = b""
        self._chunk_buf = b""
        self._chunked = False
        self._chunk_left = 0


def _crc24q_table():
    table = []
    for i in range(256):
        crc = i << 16
        for _ in range(8):
            crc <<= 1
            if crc & 0x1000000:
                crc ^= 0x1864CFB
        table.append(crc & 0xFFFFFF)
    return table


_CRC24Q = _crc24q_table()


def crc24q(data):
    crc = 0
    for byte in data:
        crc = ((crc << 8) & 0xFFFFFF) ^ _CRC24Q[(crc >> 16) ^ byte]
    return crc


class Rtcm3Scanner:
    """Finds RTCM3 frames (0xD3, 10-bit length, payload, CRC-24Q) in a byte stream and reports message types."""
    def __init__(self):
        self._buffer = bytearray()

    def feed(self, data):
        """Returns the message numbers of all complete, CRC-valid frames found."""
        self._buffer += data
        types = []
        while True:
            start = self._buffer.find(0xD3)
            if start < 0:
                self._buffer.clear()
                break
            del self._buffer[:start]
            if len(self._buffer) < 6:
                break
            length = ((self._buffer[1] & 0x03) << 8) | self._buffer[2]
            frame_len = 3 + length + 3
            if len(self._buffer) < frame_len:
                break
            frame = bytes(self._buffer[:frame_len])
            if crc24q(frame[:-3]) == int.from_bytes(frame[-3:], 'big') and length >= 2:
                types.append((frame[3] << 4) | (frame[4] >> 4))
                del self._buffer[:frame_len]
            else:
                del self._buffer[:1]  # false sync byte, keep searching
        return types
# --- End of um960_core.py ---


# -------------------------------------------------------------------------
# NMEA PARSER ENGINE
# -------------------------------------------------------------------------
class UM960Decoder:
    """
    Stateful decoder for parsing standard NMEA sentences and Unicore proprietary sentences.
    Supports: GGA, RMC, GSA, GSV, HDT and Unicore-specific $KSXT messages.
    """
    def __init__(self):
        self.latitude = 0.0
        self.longitude = 0.0
        self.altitude = 0.0
        self.speed_kmh = 0.0
        self.course_deg = 0.0
        self.heading_deg = float('nan')
        self.fix_quality = 0 # 0=Unfixed, 1=Single, 2=DGPS, 4=RTK Fixed, 5=RTK Float
        self.num_satellites = 0
        self.hdop = 1.0
        self.timestamp = ""
        self.bgs_east = float('nan')
        self.bgs_north = float('nan')
        self.bgs_lam_east = float('nan')
        self.bgs_lam_north = float('nan')
        self.gr_east = float('nan')
        self.gr_north = float('nan')

    def parse_nmea_lat_lon(self, val, dir_char):
        """Helper to convert NMEA DDMM.MMMMM into decimal degrees"""
        if not val or not dir_char:
            return 0.0
        try:
            parts = val.split('.')
            deg_digits = len(parts[0]) - 2
            deg = float(parts[0][:deg_digits])
            minutes = float(parts[0][deg_digits:] + "." + parts[1])
            decimal = deg + (minutes / 60.0)
            if dir_char in ['S', 'W']:
                decimal = -decimal
            return decimal
        except Exception:
            return 0.0

    def parse_line(self, line: str):
        """Parses a single line of NMEA. Returns True if position was updated."""
        line = line.strip()
        if not line.startswith('$'):
            return False

        # Validate checksum if possible
        if '*' in line:
            payload, checksum = line.split('*', 1)
            calculated = 0
            for char in payload[1:]:
                calculated ^= ord(char)
            try:
                if int(checksum, 16) != calculated:
                    # Ignore checksum failure occasionally but try to parse
                    pass
            except ValueError:
                pass

        parts = line.split(',')
        sentence_type = parts[0]

        updated = False

        # 1. GGA: Global Positioning System Fix Data
        if sentence_type.endswith('GGA') and len(parts) >= 10:
            self.timestamp = parts[1]
            raw_lat = parts[2]
            lat_dir = parts[3]
            raw_lon = parts[4]
            lon_dir = parts[5]
            quality = parts[6]
            num_sats = parts[7]
            hdop = parts[8]
            alt = parts[9]

            if raw_lat and raw_lon:
                self.latitude = self.parse_nmea_lat_lon(raw_lat, lat_dir)
                self.longitude = self.parse_nmea_lat_lon(raw_lon, lon_dir)
                self.altitude = float(alt) if alt else 0.0
                self.fix_quality = int(quality) if quality else 0
                self.num_satellites = int(num_sats) if num_sats else 0
                self.hdop = float(hdop) if hdop else 1.0
                updated = True

        # 2. RMC: Recommended Minimum Specific GNSS Data
        elif sentence_type.endswith('RMC') and len(parts) >= 9:
            self.timestamp = parts[1]
            status = parts[2]
            raw_lat = parts[3]
            lat_dir = parts[4]
            raw_lon = parts[5]
            lon_dir = parts[6]
            speed_knots = parts[7]
            course = parts[8]

            if status == 'A' and raw_lat and raw_lon:
                self.latitude = self.parse_nmea_lat_lon(raw_lat, lat_dir)
                self.longitude = self.parse_nmea_lat_lon(raw_lon, lon_dir)
                self.speed_kmh = float(speed_knots) * 1.852 if speed_knots else 0.0
                self.course_deg = float(course) if course else 0.0
                updated = True

        # 3. HDT / GPHDT: Heading (True)
        elif sentence_type.endswith('HDT') and len(parts) >= 2:
            hdt_val = parts[1]
            if hdt_val:
                try:
                    self.heading_deg = float(hdt_val)
                except ValueError:
                    pass

        # 4. KSXT: Unicore Proprietary integrated dual antenna positioning + orientation sentence
        # Format often resembles: $KSXT,yyyymmddhhmmss.ss,heading,pitch,roll,lat,lon,alt,ve,vn,vu,hdg_status,pos_status,sats...
        elif sentence_type == '$KSXT' and len(parts) >= 15:
            try:
                # Typically index 2 is heading, index 5 is lat, index 6 is lon, index 7 is altitude
                heading_str = parts[2]
                lat_str = parts[5]
                lon_str = parts[6]
                alt_str = parts[7]
                fix_stat = parts[12] # position status
                sat_num = parts[14]

                if lat_str and lon_str:
                    self.latitude = float(lat_str)
                    self.longitude = float(lon_str)
                    self.altitude = float(alt_str) if alt_str else 0.0
                    self.heading_deg = float(heading_str) if heading_str else float('nan')
                    self.num_satellites = int(sat_num) if sat_num else 0
                    
                    # Convert UM960 internal KSXT status code to standard GGA quality equivalent for logging
                    # 4=RTK Fixed, 5=RTK Float, etc.
                    try:
                        status_val = int(fix_stat)
                        if status_val == 4 or status_val == 62: # Typical RTK Fixed indicators
                            self.fix_quality = 4
                        elif status_val == 5 or status_val == 61: # Typical RTK Float indicators
                            self.fix_quality = 5
                        else:
                            self.fix_quality = 1
                    except Exception:
                        self.fix_quality = 1
                        
                    updated = True
            except Exception:
                pass

        if updated:
            # Perform projection coordinate transfers instantly
            self.bgs_east, self.bgs_north, self.bgs_lam_east, self.bgs_lam_north, self.gr_east, self.gr_north = convert_coordinates(
                self.latitude, self.longitude
            )

        return updated


# -------------------------------------------------------------------------
# HARDWARE / EMULATION STREAM GENERATORS
# -------------------------------------------------------------------------
class NMEAStreamer:
    """
    Manages the reading of NMEA data either from a real hardware serial port
    or from a high-quality simulated trajectory crossing Western Bulgaria & Greece.
    """
    def __init__(self, port, baud, simulate=False, rover_mode="SURVEY", check_mode=True, save_config=False,
                 nmea_messages=("GPGGA", "GPRMC"), nmea_interval=1.0):
        self.port = port
        self.baud = baud
        self.simulate = simulate
        self.rover_mode = rover_mode      # ROVER sub-type: SURVEY, UAV, AUTOMOTIVE or "" for plain ROVER
        self.check_mode = check_mode      # Query MODE on connect and switch to ROVER if needed
        self.save_config = save_config    # Persist configuration changes with SAVECONFIG
        self.nmea_messages = [m.upper() for m in nmea_messages]  # NMEA logs to enable on connect (empty = skip)
        self.nmea_interval = nmea_interval  # Output interval in seconds (1 = 1Hz, 0.2 = 5Hz)
        self.running = False
        self.decoder = UM960Decoder()
        self.queue = deque(maxlen=1000) # stores historical path: tuples of (lat, lon, bgs_e, bgs_n, gr_e, gr_n, quality)
        self.thread = None

        # Simulation path variables
        self.sim_tick = 0
        self.sim_route = "bulgaria_to_greece"

    def start(self):
        self.running = True
        self.thread = threading.Thread(target=self._run_loop, daemon=True)
        self.thread.start()

    def stop(self):
        self.running = False
        if self.thread:
            self.thread.join(timeout=1.0)

    def _handle_line(self, line_str):
        """Feeds one received line to the decoder and records the trajectory point if position updated."""
        if self.decoder.parse_line(line_str):
            # Store trajectory tuple: (lat, lon, bgs_e, bgs_n, bgs_lam_e, bgs_lam_n, gr_e, gr_n, fix_quality)
            self.queue.append((
                self.decoder.latitude, self.decoder.longitude,
                self.decoder.bgs_east, self.decoder.bgs_north,
                self.decoder.bgs_lam_east, self.decoder.bgs_lam_north,
                self.decoder.gr_east, self.decoder.gr_north,
                self.decoder.fix_quality
            ))

    def configure_receiver(self, serial_conn):
        """Checks ROVER mode and NMEA output on the receiver, see UM960Configurator."""
        UM960Configurator(
            serial_conn, on_line=self._handle_line, rover_mode=self.rover_mode, check_mode=self.check_mode,
            save_config=self.save_config, nmea_messages=self.nmea_messages, nmea_interval=self.nmea_interval
        ).configure()

    def _generate_simulated_ksxt(self, lat, lon, heading, alt, q, num_sats):
        """Generates a perfect Unicore proprietary $KSXT sentence"""
        time_str = time.strftime("%Y%m%d%H%M%S.00", time.gmtime())
        pitch = 1.2 * math.sin(self.sim_tick / 10.0)
        roll = 0.8 * math.cos(self.sim_tick / 8.0)
        # Position status: 4 for RTK fixed, 5 for RTK float, 1 for single
        pos_status = 4 if q == 4 else (5 if q == 5 else 1)
        # Calculate checksum
        payload = f"KSXT,{time_str},{heading:.2f},{pitch:.2f},{roll:.2f},{lat:.8f},{lon:.8f},{alt:.2f},0.05,0.08,0.12,3,{pos_status},{num_sats},{num_sats},1,0,0,0,10"
        
        calculated_xor = 0
        for char in payload:
            calculated_xor ^= ord(char)
        
        return f"\${payload}*{calculated_xor:02X}"

    def _generate_simulated_nmea_lines(self):
        """
        Synthesizes standard and proprietary sentences traversing Western Bulgaria and Greece.
        Route starts around Pernik/Kyustendil (Western Bulgaria) and heads South to Thessaloniki (Greece).
        """
        # Linear trajectory coordinates from Sofia (42.69, 23.32) through Promachonas (BG/GR border - 41.37, 23.36) to Thessaloniki (40.64, 22.94)
        total_steps = 300
        step = self.sim_tick % total_steps
        
        # Traverse from Sofia to Thessaloniki
        t = step / float(total_steps)
        # Starting point (Sofia, BG)
        start_lat, start_lon = 42.6976, 23.3219
        # Ending point (Thessaloniki, GR)
        end_lat, end_lon = 40.6401, 22.9444
        
        lat = start_lat + (end_lat - start_lat) * t
        lon = start_lon + (end_lon - start_lon) * t
        
        # Heading calculation
        heading = (math.degrees(math.atan2(end_lon - start_lon, end_lat - start_lat)) + 360) % 360
        # Add slight wobble for realism
        heading += 5.0 * math.sin(step / 3.0)
        
        alt = 550.0 - 500.0 * t + 15.0 * math.cos(step / 5.0)
        num_sats = int(24 + 4 * math.sin(step / 10.0))
        
        # Simulated RTK state transitions (intermittent tree canopies = float, open skies = fixed)
        if 80 < step < 110 or 200 < step < 230:
            q = 5 # RTK Float
        elif 140 < step < 160:
            q = 1 # Single GPS (no RTK)
        else:
            q = 4 # RTK Fixed (Excellent!)

        self.sim_tick += 1

        # Format longitude and latitude into DDMM.MMMM for standard GGA/RMC
        def to_nmea_deg(val, is_lat):
            sign = '-' if val < 0 else ''
            abs_val = abs(val)
            deg = int(abs_val)
            minutes = (abs_val - deg) * 60.0
            dir_char = ('S' if is_lat else 'W') if sign else ('N' if is_lat else 'E')
            deg_str = f"{deg:02d}" if is_lat else f"{deg:03d}"
            return f"{deg_str}{minutes:08.5f}", dir_char

        nmea_lat, lat_dir = to_nmea_deg(lat, is_lat=True)
        nmea_lon, lon_dir = to_nmea_deg(lon, is_lat=False)

        time_nmea = time.strftime("%H%M%S.00", time.gmtime())
        date_nmea = time.strftime("%d%m%y", time.gmtime())
        speed_knots = 45.3 / 1.852 + 2.0 * math.sin(step)

        # Build NMEA messages
        # GGA
        gga_payload = f"GNGGA,{time_nmea},{nmea_lat},{lat_dir},{nmea_lon},{lon_dir},{q},{num_sats},0.9,{alt:.1f},M,35.2,M,,"
        calculated_gga_xor = 0
        for char in gga_payload:
            calculated_gga_xor ^= ord(char)
        gga_str = f"\${gga_payload}*{calculated_gga_gga_xor:02X}" if 'calculated_gga_gga_xor' in locals() else f"\${gga_payload}*{calculated_gga_xor:02X}"

        # RMC
        rmc_payload = f"GNRMC,{time_nmea},A,{nmea_lat},{lat_dir},{nmea_lon},{lon_dir},{speed_knots:.2f},{heading:.1f},{date_nmea},,,"
        calculated_rmc_xor = 0
        for char in rmc_payload:
            calculated_rmc_xor ^= ord(char)
        rmc_str = f"\${rmc_payload}*{calculated_rmc_xor:02X}"

        # HDT
        hdt_payload = f"GNHDT,{heading:.2f},T"
        calculated_hdt_xor = 0
        for char in hdt_payload:
            calculated_hdt_xor ^= ord(char)
        hdt_str = f"\${hdt_payload}*{calculated_hdt_xor:02X}"

        # KSXT
        ksxt_str = self._generate_simulated_ksxt(lat, lon, heading, alt, q, num_sats)

        return [gga_str, rmc_str, hdt_str, ksxt_str]

    def _run_loop(self):
        serial_conn = None
        if not self.simulate:
            if serial is None:
                print("Error: Serial driver not installed. Dropping into simulation mode.")
                self.simulate = True
            else:
                try:
                    serial_conn = serial.Serial(
                        port=self.port,
                        baudrate=self.baud,
                        bytesize=serial.EIGHTBITS,
                        parity=serial.PARITY_NONE,
                        stopbits=serial.STOPBITS_ONE,
                        timeout=1.0
                    )
                    print(f"Connected successfully to UM960 serial port: {self.port} at {self.baud} baud.")
                except Exception as e:
                    print(f"Error opening serial port {self.port}: {e}. Dropping into simulation mode.")
                    self.simulate = True

                if serial_conn:
                    try:
                        self.configure_receiver(serial_conn)
                    except Exception as e:
                        print(f"Warning: UM960 configuration failed: {e}")

        while self.running:
            if self.simulate:
                lines = self._generate_simulated_nmea_lines()
                for raw_line in lines:
                    self._handle_line(raw_line)
                    time.sleep(0.05) # simulate output spacing
                time.sleep(1.0) # 1Hz positioning interval
            else:
                try:
                    if serial_conn and serial_conn.in_waiting:
                        line_bytes = serial_conn.readline()
                        line_str = line_bytes.decode('ascii', errors='ignore')
                        self._handle_line(line_str)
                except Exception as e:
                    print(f"Serial read error: {e}")
                    time.sleep(1)


# -------------------------------------------------------------------------
# REAL-TIME PLOTTING & DASHBOARD
# -------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Unicore UM960 GNSS GIS & Coordinate System Tracker")
    parser.add_argument('--port', type=str, default='/dev/ttyUSB0', help="Serial port identifier")
    parser.add_argument('--baud', type=int, default=115200, help="Serial baud rate for UM960")
    parser.add_argument('--simulate', action='store_true', default=False, help="Simulate data path without real receiver")
    parser.add_argument('--rover-mode', type=str.upper, default='SURVEY', choices=['SURVEY', 'UAV', 'AUTOMOTIVE', 'DEFAULT'],
                        help="ROVER sub-mode applied if the receiver is not already a rover (DEFAULT = plain 'MODE ROVER')")
    parser.add_argument('--skip-mode-check', action='store_true', default=False,
                        help="Do not query/reconfigure the receiver mode on connect")
    parser.add_argument('--nmea-messages', type=str, default='GPGGA,GPRMC',
                        help="Comma-separated NMEA logs to enable on the connected port ('' to skip)")
    parser.add_argument('--nmea-interval', type=float, default=1.0,
                        help="NMEA output interval in seconds (1 = 1Hz, 0.2 = 5Hz)")
    parser.add_argument('--save-config', action='store_true', default=False,
                        help="Persist configuration changes to receiver NVM with SAVECONFIG")
    args = parser.parse_args()

    # If serial library is missing, force simulation
    is_simulation = args.simulate or (serial is None)
    if is_simulation:
        print("\\n--- RUNNING IN SIMULATION DEMO MODE ---")
        print("Simulating a GNSS platform driving from Western Bulgaria (Sofia) down into Northern Greece.")
        print("Calculating exact coordinates in BGS2005 UTM 34N, BGS2005 Lambert, and HGRS87 in real-time.\\n")

    streamer = NMEAStreamer(port=args.port, baud=args.baud, simulate=is_simulation,
                            rover_mode='' if args.rover_mode == 'DEFAULT' else args.rover_mode,
                            check_mode=not args.skip_mode_check, save_config=args.save_config,
                            nmea_messages=[m.strip() for m in args.nmea_messages.split(',') if m.strip()],
                            nmea_interval=args.nmea_interval)
    streamer.start()

    # Set up real-time matplotlib plots with two subplots:
    # Left: BGS2005 grid trajectory, Right: Greek Grid trajectory
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 7))
    fig.suptitle("Unicore UM960 Geographic Coordinate Convergence Dashboard", fontsize=14, fontweight='bold')

    # Styles
    for ax in (ax1, ax2):
        ax.grid(True, linestyle='--', alpha=0.5)
        ax.set_aspect('equal')

    ax1.set_title("БГС2005 / UTM zone 34N (EPSG:7803) - Western Bulgaria", color='#0f766e', fontweight='semibold')
    ax1.set_xlabel("Easting (X) [meters]")
    ax1.set_ylabel("Northing (Y) [meters]")

    ax2.set_title("HGRS87 / Greek Grid (EPSG:2100) - Northern Greece", color='#1d4ed8', fontweight='semibold')
    ax2.set_xlabel("Easting (X) [meters]")
    ax2.set_ylabel("Northing (Y) [meters]")

    # Trajectory lines and current location points
    bgs_line, = ax1.plot([], [], 'o-', color='#0f766e', label="Track", markersize=3, markevery=5)
    bgs_curr, = ax1.plot([], [], 'X', color='#dc2626', markersize=10, label="Vehicle")
    
    greek_line, = ax2.plot([], [], 's-', color='#1d4ed8', label="Track", markersize=3, markevery=5)
    greek_curr, = ax2.plot([], [], 'X', color='#dc2626', markersize=10, label="Vehicle")

    ax1.legend()
    ax2.legend()

    # Annotation text blocks
    text_info = fig.text(0.15, 0.02, "", fontsize=10, fontfamily='monospace', 
                         bbox=dict(facecolor='white', alpha=0.9, edgecolor='#ccc', boxstyle='round,pad=0.5'))

    def update_plot(frame):
        if not streamer.queue:
            return bgs_line, bgs_curr, greek_line, greek_curr

        # Unpack the current queue components
        history = list(streamer.queue)
        
        # Transposed lists
        lats = [h[0] for h in history]
        lons = [h[1] for h in history]
        bgs_es = [h[2] for h in history if not math.isnan(h[2])]
        bgs_ns = [h[3] for h in history if not math.isnan(h[3])]
        bgs_l_es = [h[4] for h in history if not math.isnan(h[4])]
        bgs_l_ns = [h[5] for h in history if not math.isnan(h[5])]
        gr_es = [h[6] for h in history if not math.isnan(h[6])]
        gr_ns = [h[7] for h in history if not math.isnan(h[7])]
        qualities = [h[8] for h in history]

        # Get latest parsed object
        decoder = streamer.decoder

        # Update Plot 1 (BGS2005 UTM 34)
        if bgs_es and bgs_ns:
            bgs_line.set_data(bgs_es, bgs_ns)
            bgs_curr.set_data([bgs_es[-1]], [bgs_ns[-1]])
            
            # Maintain dynamic zoom centering round current point
            margin = 3000  # meters padding
            ax1.set_xlim(min(bgs_es) - margin, max(bgs_es) + margin)
            ax1.set_ylim(min(bgs_ns) - margin, max(bgs_ns) + margin)

        # Update Plot 2 (Greek Grid)
        if gr_es and gr_ns:
            greek_line.set_data(gr_es, gr_ns)
            greek_curr.set_data([gr_es[-1]], [gr_ns[-1]])
            
            margin = 3000  # meters padding
            ax2.set_xlim(min(gr_es) - margin, max(gr_es) + margin)
            ax2.set_ylim(min(gr_ns) - margin, max(gr_ns) + margin)

        # Update quality text label
        quality_map = {0: "NO FIX", 1: "GNSS Single", 2: "DGPS", 4: "RTK FIXED (Precision)", 5: "RTK FLOAT"}
        quality_text = quality_map.get(decoder.fix_quality, f"CODE {decoder.fix_quality}")

        summary = (
            f"--- Unicore UM960 Realtime Live Stats ---\\n"
            f"Time/UTC: {decoder.timestamp} | Constellation Satellites: {decoder.num_satellites} (HDOP: {decoder.hdop:.1f})\\n"
            f"WGS84 Lat/Lon: {decoder.latitude:.8f}°N, {decoder.longitude:.8f}°E | Ellipsoidal Height: {decoder.altitude:.2f} m\\n"
            f"Heading: {decoder.heading_deg:.1f}° | Speed: {decoder.speed_kmh:.1f} km/h | Fix Status: {quality_text}\\n"
            f"\\n"
            f"GRID CONVERSIONS:\\n"
            f"-> BGS2005 / UTM 34N:  Easting: {decoder.bgs_east:11.3f} m | Northing: {decoder.bgs_north:12.3f} m\\n"
            f"-> BGS2005 / Lambert:  Easting: {decoder.bgs_lam_east:11.3f} m | Northing: {decoder.bgs_lam_north:12.3f} m\\n"
            f"-> Greek Grid (Cadastre): Easting: {decoder.gr_east:11.3f} m | Northing: {decoder.gr_north:12.3f} m"
        )
        text_info.set_text(summary)

        return bgs_line, bgs_curr, greek_line, greek_curr

    # Matplotlib animated loop running at 10Hz to parse incoming blocks immediately
    anim = FuncAnimation(fig, update_plot, interval=100, blit=False, cache_frame_data=False)
    
    try:
        plt.tight_layout(rect=[0, 0.05, 1, 0.95])
        plt.show()
    except KeyboardInterrupt:
        pass
    finally:
        print("\\nStopping receiver reader threads...")
        streamer.stop()
        print("Done. Tracker terminated.")


if __name__ == "__main__":
    main()
`;
